//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dialog
    {
        public int id { get; set; }
        public string from { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> conversation_time { get; set; }
        public string to { get; set; }
    }
}
